//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.25 at 03:25:10 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://courseService.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jaxb.xml.courses;
